[theme]
base = "light"
primaryColor = "#4F4CF3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FC"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
